plugins:
  team_timezones_enabled:
    default: true
    client: true
  team_timezones_group:
    client: true
    default: 'staff'
    type: group
  team_timezones_categories:
    client: true
    default: ''
    type: category_list
    list_type: "compact"
  team_timezones_mode:
    client: true
    default: "band"
    type: enum
    choices:
      - band
      - zones
  team_timezones_availability_curve_power_function:
    client: true
    default: 6
    min: 3
    max: 12
  team_timezones_availability_origin_offset:
    client: true
    default: 0
    min: -12
    max: 12
  team_timezones_morning_start:
    client: true
    default: 9
  team_timezones_evening_start:
    client: true
    default: 18
  team_timezones_background_colour:
    client: true
    default: '#FFFFFF'
  team_timezones_available_colour:
    client: true
    default: '#0088cc'